[package]
name = "bitcoin-insights"
description = "A simple implementation in Rust of some Bitcoin features for educational purposes."
authors = ["Dzung Nguyen Mau"]
version = "0.1.0"
edition = "2024"

[dependencies]
bs58 = { version = "0.5.1", features = ["check"] }
rand = "0.10.2"
sha2 = "0.11.0"
pbkdf2 = "0.13.0"
hmac = "0.13.0"
k256 = { version = "0.14.0", features = ["ecdsa"] }
ripemd = "0.2.0"

[dev-dependencies]
cargo-husky = { version = "1", features = ["precommit-hook"] }
